// <auto-generated />
using System;
using HUAPIClassLibrary;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HUAPIClassLibrary.Migrations
{
    [DbContext(typeof(HUAPIDBContext))]
    [Migration("20180824005959_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HUAPIClassLibrary.CustomSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("Id");

                    b.ToTable("HUAPISettings");
                });

            modelBuilder.Entity("HUAPIClassLibrary.FWLink", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("Created");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.ToTable("FWLink");
                });

            modelBuilder.Entity("HUAPIClassLibrary.ScrapeQuery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CreateQ")
                        .IsRequired();

                    b.Property<DateTime>("Created");

                    b.Property<string>("DeltaQ");

                    b.Property<string>("DocType")
                        .IsRequired();

                    b.Property<string>("DropQ")
                        .IsRequired();

                    b.Property<string>("FormName")
                        .IsRequired();

                    b.Property<string>("Group")
                        .IsRequired();

                    b.Property<bool>("IsActive");

                    b.Property<int>("Order");

                    b.Property<string>("SelectQ")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ScrapeQuery");
                });
#pragma warning restore 612, 618
        }
    }
}
